version: '3.1'

services:
  database:
    image: mongo:4.2
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "12345"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  server:
    image: prim/rld-server:1.0.0
    build:
      context: "."
    restart: always
    container_name: "trx_server"
    links:
      - database
    ports:
      - "3000:3100"
      - "3100:3200"

